import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";
import {
  averageBuutonHeight,
  borderWidth,
  inputHeight,
  midButtonHeight,
  Screen,
  universalPaddingHorizontal,
  universalPaddingHorizontalMedium,
  universalPaddingTop,
  universalPaddingVertical,
} from "../theme/dimens";
import { isTablet } from "react-native-device-info";

export const styles = StyleSheet.create({
  welcomeLogo: {
    height: 70,
    width: 220,
    alignSelf: "center",
    marginTop: "20%",
    marginBottom: "15%",
  },
  alignCenter: {
    alignItems: "center",
  },
  welcomeRoleContainer: {
    flexDirection: "row",
    marginTop: "10%",
  },
  welcomeRoleBox: {
    borderColor: colors.border,
    borderWidth: borderWidth,
    borderRadius: 5,
    padding: universalPaddingVertical,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  roleIcon: {
    height: 120,
    width: 120,
  },
  textAlignCenter: {
    textAlign: "center",
  },
  loginInputContainer: {
    marginTop: "10%",
    marginHorizontal: 20,
  },
  loginButton: {
    marginTop: "10%",
  },
  homeToolContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: universalPaddingHorizontal,
    backgroundColor: colors.mainBg,
    // backgroundColor:'red',
    paddingTop: universalPaddingTop,
  },
  homeToolContainer2: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  homeToolContainer3: {
    // width: "68%",
    flex: 1,
    marginStart: 10,
  },
  homeToolContainer4: {
    flexDirection: "row",
    marginTop: 16,
    gap: 5,
    paddingHorizontal: 20,
  },
  upcomigToolContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 24,
    // width:"100%"
  },
  homeToolContainer5: {
    flexDirection: "row",
    padding: universalPaddingHorizontalMedium,
    backgroundColor: colors.white,
    gap: 10,
  },
  profileImage: {
    height: 65,
    width: 65,
    borderRadius: 100,
    marginTop:10,
    marginHorizontal: 0,
    borderWidth: 2,
    borderColor: colors.bg_one_dark,
  },
  locationIcon: {
    height: 18,
    width: 18,
  },
  downArrow: {
    height: 15,
    width: 15,
    marginStart: 10,
  },
  bellIcon: {
    height: 20,
    width: 20,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.mainBg,
    paddingHorizontal: universalPaddingHorizontal,
  },
  filterContainer: {
    height: inputHeight,
    width: inputHeight,
    backgroundColor: colors.tabItem,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    marginStart: 5,
  },
  searchInput: {
    flex: 1,
    marginEnd: 5,
  },
  appointmentSingle: {
    flex: 1,
    // paddingStart: isTablet ? "20%" : 36,
    justifyContent: "center",
    paddingHorizontal: 16,
    alignItems: "center",
    // overflow: "hidden",
    // backgroundColor:'red',
    // flexDirection:'row'
  },
  colorLine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: "black",
    width: 7,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  nearByContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 18,
    marginBottom: 8,
    marginHorizontal: 16,
  },
  doctorBoxContainer: {
    borderWidth: borderWidth,
    borderColor: colors.border,
    borderRadius: 6,
    marginTop: 10,
  },
  doctorImage: {
    height: 115,
    width: 110,
    borderRadius: 8,
  },
  department: {
    backgroundColor: colors.buttonBg,
    borderRadius: 20,
    paddingHorizontal: universalPaddingVertical,
    paddingVertical: 5,
    alignItems: "center",
    marginTop: 10,
  },
  rno: {
    backgroundColor: colors.tabItem,
    borderRadius: 20,
    paddingHorizontal: universalPaddingVertical,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
  },
  button: {
    margin: universalPaddingHorizontalMedium,
  },
  requestButton: {
    marginHorizontal: universalPaddingHorizontalMedium,
    marginBottom: 10,
  },
  button2: {
    margin: universalPaddingHorizontalMedium,
    backgroundColor: colors.loader,
  },
  button3: {
    margin: universalPaddingHorizontal,
    marginVertical: 15,
    backgroundColor: colors.loader,
    flex: 1,
    height: 50,
  },
  button4: {
    marginVertical: 15,
    marginRight: 0,
    marginLeft: universalPaddingHorizontal,
    flex: 1,
    height: averageBuutonHeight,
  },
  button5: {
    margin: universalPaddingHorizontal,
    marginVertical: 15,
    backgroundColor: colors.loader,
    flex: 1,
    height: 50,
  },
  button6: {
    marginVertical: 15,
    marginLeft: 0,
    marginRight: universalPaddingHorizontal,
    flex: 1,
    height: averageBuutonHeight,
  },
  tabbar: {
    backgroundColor: "transparent",
    shadowOpacity: 0,
    elevation: 0,
    borderBottomWidth: 0,
  },
  main: {
    flex: 1,
    backgroundColor: colors.mainBg,
  },
  mainPadding: {
    flex: 1,
    backgroundColor: colors.mainBg,
    paddingHorizontal: universalPaddingHorizontal,
  },
  mainSecond: {
    flexGrow: 1,
    backgroundColor: colors.bg_second,
  },
  featureSecondContainer: {
    borderTopColor: colors.border,
    borderTopWidth: 1,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#EFF3F566",
  },
  featurePendingContainer: {
    borderTopColor: colors.border,
    borderTopWidth: 1,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#EFF3F566",
  },
  featureRecentContainer: {
    borderTopColor: colors.border,
    borderTopWidth: 1,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: universalPaddingHorizontal,
    backgroundColor: "#EFF3F566",
  },
  borderView: {
    height: 60,
    backgroundColor: colors.border,
    width: borderWidth,
  },
  featureSecondContainer2: {
    flex: 1,
    alignItems: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    backgroundColor: colors.white,
  },
  featureSecondContainer3: {
    borderTopColor: colors.border,
    borderTopWidth: borderWidth,
    borderBottomWidth: borderWidth,
    borderBottomColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 70,
    padding: universalPaddingHorizontalMedium,
    backgroundColor: colors.border,
    opacity: 0.8,
  },
  profileContainer: {
    marginTop: 150,
  },
  profileImage2: {
    height: 140,
    width: 140,
    position: "absolute",
    alignSelf: "center",
    top: 60,
    borderWidth: borderWidth,
    borderColor: colors.bg_one_dark,
    borderRadius: 70,
    backgroundColor: colors.white,
    zIndex: 1,
  },
  profileInfo: {
    marginTop: 10,
    alignItems: "center",
  },
  profileInfoBox: {
    flexGrow: 1,
    marginTop: 130,
    alignItems: "center",
    backgroundColor: colors.white,
  },
  idContainer: {
    backgroundColor: colors.loader,
    paddingHorizontal: universalPaddingHorizontal,
    paddingVertical: 5,
    borderRadius: 20,
    marginTop: 10,
  },
  specialtyContainer: {
    marginBottom: 30,
  },
  feesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 20,
  },
  feeStyle: {
    textAlignVertical: "center",
  },
  aboutContainer: {
    backgroundColor: colors.bg_second,
    borderRadius: 10,
    padding: universalPaddingHorizontal,
  },
  requestButtonContainer: {
    marginTop: 10,
    flex: 1,
    paddingBottom: 10,
    justifyContent: "flex-end",
    paddingHorizontal: universalPaddingHorizontal,
    backgroundColor: colors.mainBg,
  },
  requestBottomContainer: {
    marginTop: 20,
  },
  inputContainer: {
    marginTop: 15,
    height: inputHeight,
    borderWidth: borderWidth,
    borderColor: colors.border,
    borderRadius: 5,
    paddingHorizontal: universalPaddingHorizontal,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    flex: 1,
  },
  appointmentTypeContainer: {
    flexDirection: "row",
    // marginTop: 10,
  },
  typeText: {
    // marginTop: 15,
  },
  calenderStyle: {
    justifyContent: "space-between",
  },
  forgotPassword: {
    alignSelf: "flex-end",
    marginTop: 10,
  },
  resetPassword: {
    marginTop: 20,
  },
  searchProfileButton: {
    marginTop: "10%",
    backgroundColor: colors.loader,
  },
  startMeeting: {
    margin: universalPaddingHorizontalMedium,
    backgroundColor: colors.loader,
    paddingHorizontal: 20,
  },
  sendMessage: {
    margin: universalPaddingHorizontalMedium,
    paddingHorizontal: 20,
  },
  sendMessageBottomSheet: {
    alignSelf: "center",
  },
  messageBox: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  rejectionBox: {
    marginTop: 10,
    flex: 1,
  },
  messageContainer: {
    borderWidth: 0.5,
    padding: 20,
    borderRadius: 8,
    marginVertical: 10,
    flexDirection: "row",
  },
  submit: {
    marginHorizontal: 16,
  },
  or: {
    alignSelf: "center",
    marginVertical: 20,
  },
  orContainer: {
    height: 32,
    width: 32,
    borderRadius: 50,
    backgroundColor: colors.white,
    elevation: 10,
    alignSelf: "center",
    marginTop: 40,
  },
  orText: {
    alignSelf: "center",
    textAlignVertical: "center",
    flex: 1,
  },
  time: {
    borderWidth: 2,
    width: 96,
    height: 50,
    borderRadius: 4,
    textAlignVertical: "center",
    justifyContent: "center",
    borderColor: colors.border,
    textAlign: "center",
    paddingVertical: 10,
  },
  timeContainer: {
    flexDirection: "row",
    marginTop: 10,
    marginHorizontal: 5,
  },
  appointment: {
    flexDirection: "row",
    justifyContent: "space-between",
    flex: 1,
    padding: universalPaddingHorizontalMedium,
  },
  pendingDate: {
    textAlignVertical: "center",
  },
  statusContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    alignItems: "center",
  },
  status: {
    backgroundColor: colors.loader,
    borderRadius: 20,
    paddingHorizontal: universalPaddingVertical,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
  },
  rnoStyle: {
    backgroundColor: colors.loader,
    borderRadius: 20,
    paddingHorizontal: universalPaddingVertical,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
    marginLeft: 8,
  },
  meetingReport: {
    alignSelf: "center",
  },
  meetingBottom: {
    marginHorizontal: 16,
    flex: 1,
  },
  cameraIcon: {
    height: 20,
    width: 20,
    alignSelf: "center",
  },
  imageContainer: {
    borderWidth: 2,
    height: 120,
    width: 120,
    borderColor: colors.border,
    borderStyle: "dashed",
    borderRadius: 8,
    // marginTop: 16,
    justifyContent: "center",
  },
  uploadText: {
    alignSelf: "center",
  },
  documentContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 20,
    gap: 5,
  },
  fileSize: {
    marginTop: 14,
  },
  typeHereBox: {
    // borderWidth: 1,
    // // height: 140,
    // borderRadius: 6,
    marginTop: 15,
    // height: inputHeight,
    borderWidth: borderWidth,
    borderColor: colors.border,
    borderRadius: 5,
    paddingHorizontal: universalPaddingHorizontal,
    // flexDirection: "row",
    // alignItems: "center",
    backgroundColor: colors.white,
    minHeight: 100,
    marginBottom: 100,
  },
 
  submitButton: {
    marginVertical: 16,
    marginHorizontal: 16,
  },
  submitButtonContainer: {
    elevation: 10,
    backgroundColor: colors.mainBg,
  },
  sendMessageSubmitButton: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: universalPaddingHorizontal,
    elevation: 10,
    backgroundColor: colors.mainBg,
  },
  message: {
    left: 10,
  },
  downloadIcon: {
    height: 18,
    width: 18,
    justifyContent: "center",
    flex: 1,
    alignSelf: "flex-end",
    // marginRight: 6,
  },
  downloadContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "60%",
  },
  drdownloadContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  rescheduleButton: {
    marginHorizontal: universalPaddingHorizontal,
    backgroundColor: colors.buttonBg,
    marginBottom: 16,
    // flex: 1,
    // marginEnd: 5,
    height: 50,
    // marginStart: 5,
  },
  meetingLinkButton: {
    marginHorizontal: universalPaddingHorizontalMedium,
    backgroundColor: colors.buttonBg,
    // flex: 1,
    marginBottom: 16,
    height: averageBuutonHeight,
  },
  typeOfAppointment: {
    marginTop: 30,
  },
  appointmentContainer: {
    borderWidth: 0.5,
    padding: 20,
    borderRadius: 8,
    marginVertical: 10,
    flexDirection: "row",
    height: 60,
  },
  appointmentBox: {
    width: "48%",
  },
  feeType: {
    marginTop: 20,
  },
  // upcomingImage: {
  //   height: 140,
  //   // width: "96%",
  //   width:329,
  //   marginHorizontal: 16,
  // },
  upcomingImage: {
    height: 170,
    width: Screen.Width - 32,
    marginVertical: 8,
    // paddingStart: 36,
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 8,
    paddingHorizontal: 35,
  },
  meetingContainer: {
    backgroundColor: colors.border,
    // height: 150,
    marginTop: 16,
    marginBottom: 40,
  },
  bottomDateContainer: {
    marginBottom: 20,
    marginHorizontal: 16,
  },
  noDoctorsFound: {
    alignSelf: "center",
    marginTop: 50,
  },
  selfieCamera1: {
    height: 100,
    width: 100,
    alignSelf: "center",
  },
  endMeetingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  subContainer1: {
    marginHorizontal: 6,
    marginBottom: 100,
    marginTop: 10,
  },
  selfieContainer: {
    height: 100,
    borderColor: colors.border,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 16,
    // marginHorizontal:40,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
  },
  selfieCamera: {
    height: 20,
    width: 18,
  },
  textStyle: {
    textAlign: "center",
    marginTop: 10,
  },
  pdf: {
    // flex: 1,
    width: 80,
    height: 80,
  },
  orTextContainer: {
    backgroundColor: colors.white,
    alignItems: "center",
    elevation: 5,
    alignSelf: "center",
    width: 60,
    height: 60,
    borderRadius: 30,
    marginTop: 20,
  },
  pdf_two: {
    // borderWidth: 2,
    height: 100,
    width: 100,
    // borderColor: colors.border,
    // borderStyle: "dashed",
    borderRadius: 8,
    // marginTop: 16,
    justifyContent: "center",
    alignSelf: "center",
  },
  ratingBtnStyle: {
    paddingHorizontal: 10,
    paddiingVertical: 5,
    backgroundColor: "#FFD700",
    alingItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },
  ratingContainer: {
    flexDirection: "row",
    gap: 10,
  },
  versionCodeContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
});
